---
parameters:
  - name: elviaDomain
  - name: elviaRuntimeEnvironment
  - name: elvidAuthority
  - name: elvidClientId
  - name: elvidRedirectUri
  - name: elvidScope

jobs:
  - deployment: Deploy
    displayName: Deploy ${{ parameters.elviaRuntimeEnvironment }}
    environment: ${{ parameters.elviaRuntimeEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              displayName: "Modify Manifest File"
              inputs:
                targetType: "inline"
                script: >
                  sed
                  --expression "s/:image-tag-value/:${{ parameters.elviaRuntimeEnvironment }}-$(Build.BuildNumber)/"
                  --expression "s/onetime-elvia-domain-value/onetime.${{ parameters.elviaDomain }}/"
                  --expression "s/elvid-elvia-domain-value/vault.${{ parameters.elviaDomain }}/"
                  --expression "s/elvid-authority-value/elvid.${{ parameters.elviaDomain }}/"
                  --expression "s/elvid-client-id-value/${{ parameters.elvidClientId }}/"
                  --expression "s/elvid-redirect-uri-value/onetime.${{ parameters.elviaDomain  }}/"
                  --expression "s/elvid-scope-value/${{ parameters.elvidScope }}/"
                  $(Pipeline.Workspace)/CI/manifest.yaml > manifest_modified.yaml
            - task: Bash@3
              displayName: "Display Manifest File"
              inputs:
                targetType: "inline"
                script: >
                  cat manifest_modified.yaml
            - task: KubernetesManifest@0
              displayName: "Deploy"
              inputs:
                kubernetesServiceConnection: RuntimeServiceKubernetes${{ parameters.elviaRuntimeEnvironment }}
                namespace: onetime
                manifests: manifest_modified.yaml
            - task: PowerShell@2
              displayName: "GET https://onetime.${{ parameters.elviaDomain }}/"
              inputs:
                failOnStderr: true
                targetType: "filePath"
                filePath: $(Pipeline.Workspace)/CI/InvokeRequestWithRetries.ps1
                arguments: >
                  -URI "https://onetime.${{ parameters.elviaDomain }}"
                  -Method "GET"
                  -Retries 5
                  -SecondsDelay 2
                  -TimeoutSec 5
