---
parameters:
  - name: domain
  - name: environment

jobs:
  - deployment: Deploy
    displayName: Deploy ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: 'sed -e "s/:imagetag/:${{ parameters.environment }}-$(Build.BuildNumber)/" -e "s/onetimeelviadomain/onetime.${{ parameters.domain }}/" $(Pipeline.Workspace)/CI/manifest.yaml > manifest_modified.yaml'
            - task: KubernetesManifest@0
              displayName: Deploy
              inputs:
                kubernetesServiceConnection: RuntimeServiceKubernetes${{ parameters.environment }}
                namespace: onetime
                manifests: manifest_modified.yaml
            - task: PowerShell@2
              displayName: 'GET https://onetime.dev-elvia.io/'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(Pipeline.Workspace)/CI/InvokeRequestWithRetries.ps1
                arguments: >
                  -URI "https://onetime.${{ parameters.domain }}"
                  -Method "GET"
                  -Retries 5
                  -SecondsDelay 2
                  -TimeoutSec 5
