---
parameters:
  - name: elviaDomain
  - name: elviaRuntimeEnvironment

jobs:
  - deployment: Deploy
    displayName: Deploy ${{ parameters.elviaRuntimeEnvironment }}
    environment: ${{ parameters.elviaRuntimeEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              displayName: "Modify Manifest File"
              inputs:
                targetType: "inline"
                script: >
                  sed
                  --expression "s/:image-tag-value/:${{ parameters.elviaRuntimeEnvironment }}-$(Build.BuildNumber)/"
                  --expression "s/elvia-vault-value/vault.${{ parameters.elviaDomain }}/"
                  --expression "s/onetime-url-value/onetime.${{ parameters.elviaDomain  }}/"
                  $(Pipeline.Workspace)/CI/manifest.yaml > manifest_modified.yaml

                  cat --show-all manifest_modified.yaml
            - task: KubernetesManifest@0
              displayName: "Deploy"
              inputs:
                kubernetesServiceConnection: RuntimeServiceKubernetes${{ parameters.elviaRuntimeEnvironment }}
                namespace: onetime
                manifests: manifest_modified.yaml
            - task: PowerShell@2
              displayName: "GET https://onetime.${{ parameters.elviaDomain }}/health"
              inputs:
                failOnStderr: true
                targetType: "filePath"
                filePath: $(Pipeline.Workspace)/CI/InvokeRequestWithRetries.ps1
                arguments: >
                  -URI "https://onetime.${{ parameters.elviaDomain }}/health"
                  -Method "GET"
                  -Retries 5
                  -SecondsDelay 2
                  -TimeoutSec 5
