---
# Source: elvia-deployment/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: yopass
  namespace: onetime
  labels:
    app: yopass
spec:
  ports:
  - name: yopassport
    port: 1337
  - name: yopassprometheusport
    port: 2112
 
  selector:
    app: yopass
---
# Source: elvia-deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
  namespace: onetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yopass
      microservice-type: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yopass
        microservice-type: worker
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: yopass
      imagePullSecrets:
      - name: containerregistryelvia
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        supplementalGroups: [65532]
      containers:
      - name: yopass
        image: containerregistryelvia.azurecr.io/onetime-yopass:imagetag        
        env:
        - name: VAULT_ADDR
          value: https://vaultelviadomain
        - name: ROLE
          value: yopass
        - name: MOUNT_PATH
          value: kubernetes/runtimeservice/onetime/yopass
        args:
        - "--metrics-port=2112"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
# Source: elvia-deployment/templates/service-monitor.yaml
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: yopass
  namespace: onetime
spec:
  endpoints:
  - port: yopassprometheusport
  selector:
    matchLabels:
      app: yopass
---
# Source: elvia-deployment/templates/ingressroute.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yopass
  namespace: onetime
spec:
  routes:
  - kind: Rule
    match: Host(`onetimeelviadomain`)
    middlewares:
    - name: hsts-header
      namespace: dns
    - name: remove-metrics
      namespace: dns
    services:
      - name: yopass
        port: 1337
