---
trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerRegistry: "ContainerRegistryElvia"
  imageTag: $(Build.BuildNumber)
  name: yopass
  namespace: onetime

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: BuildDev
    dependsOn: []
    variables:
      imageTag: dev-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.dev
  - stage: BuildTest
    dependsOn: []
    variables:
      imageTag: test-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.test
  - stage: BuildProd
    dependsOn: []
    variables:
      imageTag: prod-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.prod

  - stage: DeployDev
    dependsOn: [BuildDev]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: dev
          elviaDomain: dev-elvia.io
          elvidAuthority: "https://elvid.test-elvia.io/"
          elvidClientId: "63db1528-e12a-455e-ad21-2bf929692c5d"
          elvidRedirectUri: "https://onetime.dev-elvia.io/callback"
          elvidScope: "ad_groups email onetime.useraccess openid profile"

  - stage: DeployTest
    dependsOn: [BuildTest, DeployDev]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: test
          elviaDomain: test-elvia.io
          elvidAuthority: "https://elvid.test-elvia.io/"
          elvidClientId: "9e8b4a79-68a8-42cc-9838-2d6c576f3fe5"
          elvidRedirectUri: "https://onetime.test-elvia.io/callback"
          elvidScope: "ad_groups email onetime.useraccess openid profile"

  - stage: DeployProd
    dependsOn: [BuildProd, DeployTest]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: prod
          elviaDomain: elvia.io
          elvidAuthority: "https://elvid.elvia.io/"
          elvidClientId: "49d2f4e8-ec65-4351-b2f9-6c997f9e4e82"
          elvidRedirectUri: "https://onetime.elvia.io/callback"
          elvidScope: "ad_groups email onetime.useraccess openid profile"
