---
trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerRegistry: "ContainerRegistryElvia"
  imageTag: $(Build.BuildNumber)
  name: yopass
  namespace: onetime

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: Build
    dependsOn: []
    variables:
      imageTag: dev-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: src/api/Dockerfile
          dockerBuildContext: src/api
          pushImageOnPR: true

  - stage: DeployDev
    dependsOn: [Build]
    variables:
    - group: vault_default_approle
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "dev"
          elviaDomain: "dev-elvia.io"
      # - template: smoketests-with-playwright.yaml
      #   parameters:
      #     environment: dev
          

  - stage: DeployTest
    dependsOn: [DeployDev]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "test"
          elviaDomain: "test-elvia.io"
          

  - stage: DeployProd
    dependsOn: [DeployTest]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "prod"
          elviaDomain: "elvia.io"
