trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerregistry: 'ContainerRegistryElvia'
  imagetag: $(Build.BuildNumber)
  name: yopass
  namespace: onetime

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: BuildDev
    dependsOn: []
    variables:
      imagetag: dev-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.dev
  - stage: BuildTest
    dependsOn: []
    variables:
      imagetag: test-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.test
  - stage: BuildProd
    dependsOn: []
    variables:
      imagetag: prod-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.prod

  - stage: DeployDev
    dependsOn: [BuildDev]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          environment: dev
          domain: dev-elvia.io

  - stage: DeployTest
    dependsOn: [BuildTest, DeployDev]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          environment: test
          domain: test-elvia.io

  - stage: DeployProd
    dependsOn: [BuildProd, DeployTest]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          environment: prod
          domain: elvia.io
