---
trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerRegistry: "ContainerRegistryElvia"
  imageTag: $(Build.BuildNumber)
  name: yopass
  namespace: onetime

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: BuildDev
    dependsOn: []
    variables:
      imageTag: dev-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.dev

  - stage: DeployDev
    dependsOn: [BuildDev]
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "dev"
          elviaDomain: "dev-elvia.io"
          elvidAuthority: "elvid.test-elvia.io"
          elvidClientId: "63db1528-e12a-455e-ad21-2bf929692c5d"
          elvidScope: "ad_groups email onetime.useraccess openid profile"
          
  - stage: BuildTest
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      imageTag: test-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.test

  - stage: DeployTest
    dependsOn: [BuildTest, DeployDev]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "test"
          elviaDomain: "test-elvia.io"
          elvidAuthority: "elvid.test-elvia.io"
          elvidClientId: "9e8b4a79-68a8-42cc-9838-2d6c576f3fe5"
          elvidScope: "ad_groups email onetime.useraccess openid profile"

  - stage: BuildProd
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      imageTag: prod-$(Build.BuildNumber)
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile.prod

  - stage: DeployProd
    dependsOn: [BuildProd, DeployTest]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: templates/deploy.yaml
        parameters:
          elviaRuntimeEnvironment: "prod"
          elviaDomain: "elvia.io"
          elvidAuthority: "elvid.elvia.io"
          elvidClientId: "49d2f4e8-ec65-4351-b2f9-6c997f9e4e82"
          elvidScope: "ad_groups email onetime.useraccess openid profile"
