---
trigger:
  batch: false
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

pr:
  autoCancel: true
  branches:
    include:
      - "features/*"
    exclude:
      - "features/experimental/*"
  paths:
    exclude:
      - "README.md"
  drafts: true

schedules:
  - cron: "0 14 * * *" # 00:00 AEST is 14:00 UTC
    displayName: "Daily Build"
    branches:
      include:
        - master

variables:
  containerRegistry: "ContainerRegistryElvia"
  imageTag: $(Build.BuildNumber)
  name: yopass
  namespace: onetime
  PIPELINE_VARIABLE: "Pipeline"

pool:
  vmImage: "ubuntu-latest"

# container: mcr.microsoft.com/playwright:focal

stages:
  - stage: "FirstStage"
    displayName: "First Stage"
    dependsOn: []
    condition: "succeededOrFailed()"
    variables:
      - name: myReadOnlyVar
        value: myValue
        readonly: true
      - name: "STAGE_VARIABLE"
        value: "Stage"
    jobs:
      - job: "FirstJob"
        displayName: "First Job"
        continueOnError: true
        workspace:
          clean: outputs
        variables:
          JOB_VARIABLE: "Job"
        steps:
          - script: "echo First Job!"
          - script: "echo $(PIPELINE_VARIABLE) $(STAGE_VARIABLE) $(JOB_VARIABLE)"

  - stage: "Playwright"
    displayName: "Playwright"
    dependsOn: []
    variables:
      - group: "playwright"
    jobs:
      - job: "PlaywrightJob"
        displayName: "Playwright Job"
        continueOnError: true
        container: mcr.microsoft.com/playwright:focal
        steps:
          - checkout: self
            clean: true
            fetchDepth: 5
            lfs: false
          - bash: |
              which bash
              echo Hello ${helloName}
            displayName: "Multiline Bash Commands"
            env:
              helloName: Playwright
          - bash: |
              ls -aln $(Pipeline.Workspace)/s
              yarn
              yarn run lint
              yarn run playwright-ci
            displayName: "Multiline Playwright Commands"
            workingDirectory: "$(Pipeline.Workspace)/s/website/playwright"
