# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: yopass
namespace: core
microserviceType: webapi
replicaCount: 1

image:
  repository: containerregistryelvia.azurecr.io/core-yopass

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 200Mi

service:
  port: 1337

env:
- name: PUBLIC_URL
  value: https://core.dev-elvia.io/yopass
- name: REACT_APP_BACKEND_URL
  value: https://core.dev-elvia.io/yopass

ingress:
  subdomain: core
  path: "/yopass"
