# name: Sync Fork

# on:
#   schedule:
#     - cron: '0 6 * * *' # at 06:00
#   workflow_dispatch: # on button click

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: tgymnich/fork-sync@v1.2.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           owner: jhaals
#           base: master
#           head: master
