name: Playwright
on: [push, pull_request]
jobs:
  jobId:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
      - name: Fix OIDC Callback
        run: |
          cd website
          sed --in-place "s|https://onetime.dev-elvia.io|http://localhost:3000|g" .env.development
          cat --show-all .env.development
      - name: Install Yarn
        run: npm install --global yarn
      # Workaround “Failed to Launch Browsers” Playwright Errors
      # https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9
      - name: Install Playwright
        run: |
          set -o xtrace;
          cd website;
          yarn add --dev playwright;
          npx playwright install;
          du --human-readable --summarize ${HOME}/.cache/ms-playwright/;
          ls --all --numeric --literal --human-readable ${HOME}/.cache/ms-playwright/;
          set +o xtrace;
      - name: Display Versions
        run: |
          set -o xtrace;
          cat /etc/*-release;
          node --version;
          yarn --version;
          cd website;
          npx playwright --version;
          echo "\${GITHUB_WORKSPACE}: ${GITHUB_WORKSPACE}"
          set +o xtrace;
      - name: Install Dependencies
        run: cd website && yarn install
      - name: Yarn Lint
        run: cd website && yarn run lint
      # "Error: ENOSPC: System limit for number of file watchers reached."
      # Workaround for read-only system configuration files.
      # CHOKIDAR_USEPOLLING=1
      # https://stackoverflow.com/a/56272746
      - name: Playwright Tests
        run: |
          cd website
          CHOKIDAR_USEPOLLING=1 yarn run playwright-ci
        env:
          ONETIME_TEST_USER_EMAIL: ${{ secrets.ONETIME_TEST_USER_EMAIL }}
          ONETIME_TEST_USER_PASSWORD: ${{ secrets.ONETIME_TEST_USER_PASSWORD }}
          CYPRESS_ONETIME_TEST_USER_EMAIL: ${{ secrets.CYPRESS_ONETIME_TEST_USER_EMAIL }}
          CYPRESS_ONETIME_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_ONETIME_TEST_USER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-artifact
          path: "$GITHUB_WORKSPACE/website/playwright/empty_storage_state.json"
          if-no-files-found: error
          retention-days: 1
